### ISSUE TITLE
More than 2 level of children

### ISSUE THREAD

**Issue by metawise** [thebatclaudio/wp-rest-api-v2-menus#16]
The plugin not supporting more than 2 levels of menus.

**Comment by marcel-silva** [comment]
I was able to achieve that by editing the code a bit.

The "wp_api_v2_menus_get_menu_items' function to be more specific.

See image:
![image](https://user-images.githubusercontent.com/18476252/59741911-af549980-92af-11e9-91ce-bce9c858d333.png)

**Comment by metawise** [comment]
Awesome! I will try that. I was able to achieve with the different plugin but this one seems later version.

**Comment by thebatclaudio** [comment]
Hi, I resolved the issue implementing a new function to check menu item's relatives. I will release a new version of the plugin ASAP.

**Comment by josias-r** [comment]
> I was able to achieve that by editing the code a bit.
> 
> The "wp_api_v2_menus_get_menu_items' function to be more specific.
> 
> See image:
> ![image](https://user-images.githubusercontent.com/18476252/59741911-af549980-92af-11e9-91ce-bce9c858d333.png)

Replace the line `unset($menu_items[$key2])` with `array_splice($menu_items, $key2, 1)`. Otherwise the array won't start at an index of 0, which will cause a problem when fetching it as JSON, because JSON converts arrays into objects when the index doesn't start with 0. (Which caused the problem for me that I couldn't use array.map() inside a React application)

Reference: [Stackoverflow](https://stackoverflow.com/questions/35672604/unset-converts-array-into-object)

@thebatclaudio

**Comment by thebatclaudio** [comment]
Hi @josias-r,
thank you for your advice. I will fix it ASAP.

**Comment by thebatclaudio** [comment]
I created another issue (#18)
